{"name":"GBQ - New Zealand BPI","description":"","version":"1.0","culture":"en-US","modifiedTime":"2023-04-24T20:48:10.0114847+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"BPI_Sep2022":{"queryId":"80d479ea-7394-4e5f-bf12-0c553bd35931","queryName":"BPI_Sep2022","loadEnabled":true}},"document":"section Section1;\r\nshared BPI_Sep2022 = let\n  Source = GoogleBigQuery.Database([BillingProject = null, UseStorageApi = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"grand-citadel-384718\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"NewZealandAnalysis\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"BPI_Sep2022\", Kind = \"Table\"]}[Data],\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Navigation 2\", \"Positve Value Flag\", each if [Data_value] > 0 then -1 else 0),\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Inserted conditional column\", {{\"Positve Value Flag\", type text}}),\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Positve Value Flag\", null}})\nin\n  #\"Replace errors\";\r\n","connectionOverrides":[{"path":"GoogleBigQuery","kind":"GoogleBigQuery","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"GoogleBigQuery\",\"path\":\"GoogleBigQuery\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"BPI_Sep2022","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"BPI_Sep2022.csv"},"attributes":[{"name":"Series_reference","dataType":"string"},{"name":"Period","dataType":"double"},{"name":"Data_value","dataType":"double"},{"name":"STATUS","dataType":"string"},{"name":"UNITS","dataType":"string"},{"name":"Subject","dataType":"string"},{"name":"Group","dataType":"string"},{"name":"Series_title_1","dataType":"string"},{"name":"Series_title_2","dataType":"string"},{"name":"Series_title_3","dataType":"string"},{"name":"Series_title_4","dataType":"string"},{"name":"Series_title_5","dataType":"string"},{"name":"Positve Value Flag","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2023-04-24T20:48:25.8720509+00:00","location":"https://wabieus2cdsap1.blob.core.windows.net:443/e0fd3feb-a359-469c-8bb1-99ac7075e9c0/BPI_Sep2022.csv?snapshot=2023-04-24T20%3A48%3A25.8609287Z"}]}]}
